<?
$PERM["kabinet-pokupatelya"]["G1"]="X";
$PERM["kabinet-pokupatelya"]["G7"]="X";
$PERM["kabinet-prodavtsa"]["G8"]="X";
$PERM["kabinet-prodavtsa"]["G1"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["/"]["*"]="R";
?>