<?
$PERM["kabinet-pokupatelya"]["9"]="X";
$PERM["kabinet-pokupatelya"]["7"]="X";
$PERM["bitrix"]["9"]="D";
$PERM["/"]["*"]="R";
$PERM["/"]["G9"]="X";
$PERM["obyavleniya"]["*"]="X";
$PERM["o-servise"]["G9"]="X";
$PERM["kabinet-prodavtsa"]["G8"]="X";
$PERM["kabinet-prodavtsa"]["G1"]="X";
$PERM["kabinet-prodavtsa"]["G9"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>